LoVisto/ProyectoFinal/LoVisto/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.pagina_principal),
    path('usuario/<str:llave>',views.pagina_usuario),
    path('informacion', views.pagina_informacion),
    path('aportaciones', views.pagina_aportaciones),
    path('<str:llave>',views.pagina_aportacion)
]

LoVisto/ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('login/', LoginView.as_view()),
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view()),
    path('', include('LoVisto.urls'))

]

LoVisto/ProyectoFinal/LoVisto/models.py
from django.db import models

# Create your models here.

class Recursos(models.Model):

    RECURSOS=[
        ('WIK', 'wikipedia'),
        ('AEM','aemet'),
        ('RED', 'reddit'),
        ('YUT','youtube'),
        ('NR','other')]

    recurso = models.CharField(max_length=3, choices=RECURSOS)

    def __str__(self):
       return str(self.id) + ":" + self.recurso

class Datos(models.Model):

    noticia = models.CharField(max_length=64)
    url = models.TextField()
    usuario = models.TextField()

    megusta = models.IntegerField()
    nomegusta = models.IntegerField()

    ncomentarios = models.IntegerField()
    recurso = models.ManyToManyField(Recursos) #Mirar si hace falta
    fecha = models.DateTimeField('published')

    def __str__(self):
       return self.noticia + ":" + self.url

class Comentarios(models.Model):

    datos = models.ForeignKey(Datos,on_delete=models.CASCADE)
    titulo = models.CharField(max_length=150) #Mirar si hace falta
    comentario = models.TextField()
    url = models.TextField(default = "No hay imagen")
    usuario = models.TextField()
    fecha = models.DateTimeField('published')

    def __str__(self):
        return self.titulo + ":" + self.comentario

class Votos(models.Model):

    datos = models.ForeignKey(Datos,on_delete=models.CASCADE)
    usuario = models.TextField()
    valor = models.TextField()

    def __str__(self):
       return str(self.datos) + ":" + self.usuario

LoVisto/ProyectoFinal/LoVisto/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from .models import Datos, Votos, Comentarios
from django.contrib.auth import logout
from django.utils import timezone
import requests
from django.http import JsonResponse
from bs4 import BeautifulSoup
from django.http import HttpResponse
from django.template import loader

@csrf_exempt
def pagina_principal(request):
    modo=0
    if request.method == "POST":
        action = request.POST['action']

        if action == "Login":
            return redirect('login/')

        elif action == "Modo_Oscuro":
            modo = 1

        elif action == "Modo_Claro":
            modo= 0

        elif action == "Logout":
            logout(request)
            return redirect('/')

        elif action == "Insertar":
            noticia = request.POST['noticia']
            url = request.POST['url']

            try:
                c = Datos.objects.get(noticia=noticia)
                c.delete()

            except Datos.DoesNotExist:
                c = Datos(noticia=noticia,url=url,usuario=request.user.username,megusta=0,nomegusta=0,ncomentarios=0,fecha=timezone.now())
                c.save()

        elif action == "Datos Usuario":
            return redirect('/usuario/' + request.user.username)

        elif action == "Aportaciones":
            return redirect('/aportaciones')

        elif action == "Informacion":
            return redirect('/informacion')

    datos_list = Datos.objects.all()
    datos_list = list(reversed(datos_list))
    datos_list_10 = datos_list[0:10]
    datos_list_3 = datos_list[0:3]
    aportaciones = 10
    megusta = 0
    nomegusta = 0
    ncomentarios = 0
    modo = modo

    context = {
        'datos_list_10': datos_list_10,
        'datos_list_3': datos_list_3,
        'datos_list': datos_list,
        'apartaciones': aportaciones,
        'megusta': megusta,
        'nomegusta':nomegusta,
        'ncomentarios': ncomentarios,
        'modo':modo
    }
    return render(request, 'LoVisto/PaginaPrincipal.html', context)

def pagina_usuario(request,llave):

    modo = 0
    if request.method =="POST":
        action=request.POST['action']

        if action== "Logout":
            logout(request)
            return redirect('/')
        elif action == "Modo_Oscuro":
            modo = 1

        elif action == "Modo_Claro":
            modo= 0

        elif action == "Inicio":
            return redirect('/')

        elif action== "Informacion":
            return redirect('/informacion')

        elif action== "Aportaciones":
            return redirect('/aportaciones')

    datos_list = Datos.objects.all()
    comentarios_list = Comentarios.objects.all()
    votos_list = Votos.objects.all()
    datos_list_3 = datos_list[0:3]
    modo=modo

    context = {
         'datos_list': datos_list,
         'comentarios_list': comentarios_list,
         'votos_list':votos_list,
         'datos_list_3':datos_list_3,
         'modo':modo

     }
    return render(request,'LoVisto/PaginaUsuario.html',context)

def pagina_informacion(request):
    modo=0
    if request.method =="POST":
        action=request.POST['action']

        if action == "Inicio":
            return redirect('/')

        elif action == "Login":
            return redirect('login/')

        elif action == "Modo_Oscuro":
            modo = 1

        elif action == "Modo_Claro":
            modo= 0

        elif action== "Logout":
            logout(request)
            return redirect('/')

        elif action== "Informacion":
            return redirect('/informacion')

        elif action == "Datos Usuario":
            return redirect('/usuario/'+request.user.username)

        elif action== "Aportaciones":
            return redirect('/aportaciones')

    datos_list= Datos.objects.all()
    datos_list_3 = datos_list[0:3]
    modo=modo

    context={
        'datos_list_3': datos_list_3,
        'modo':modo
    }

    return render(request,'LoVisto/PaginaInformacion.html',context)


def pagina_aportaciones(request):
    modo=0
    if request.method == "POST":
        action = request.POST['action']

        if action == "Inicio":
            return redirect('/')

        elif action == "Logout":
            logout(request)
            return redirect('/')

        elif action == "Login":
            return redirect('login/')

        elif action == "Modo_Oscuro":
            modo = 1

        elif action == "Modo_Claro":
            modo= 0

        elif action == "Datos Usuario":
            return redirect('/usuario/' + request.user.username)

        elif action == "Informacion":
            return redirect('/informacion')

    datos_list = list(reversed(Datos.objects.all()))
    comentarios_list = Comentarios.objects.all()
    votos_list = Votos.objects.all()
    datos_list_3 = datos_list[0:3]
    modo=modo

    context = {
        'datos_list': datos_list,
        'comentarios_list': comentarios_list,
        'votos_list': votos_list,
        'datos_list_3': datos_list_3,
        'modo':modo
    }

    return render(request, 'LoVisto/PaginaAportaciones.html', context)

def pagina_aportacion(request,llave):
    modo=0
    if request.method =="PUT":
        valor = request.body.decode('utf-8')

    if request.method =="POST":
        action = request.POST['action']
        noticia = llave

        if action == "Inicio":
            return redirect('/')

        elif action == "Logout":
            logout(request)
            return redirect('/')

        elif action == "Login":
            return redirect('login/')

        elif action == "Modo_Oscuro":
            modo = 1

        elif action == "Modo_Claro":
            modo= 0

        elif action == "Datos Usuario":
            return redirect('/usuario/' + request.user.username)

        elif action == "Informacion":
            return redirect('/informacion')

        elif action== "Aportaciones":
            return redirect('/aportaciones')

        elif action == "Cambiar contenido":
            try:
                c= Datos.objects.get(noticia=llave)
                c.url=request.POST['valor']
                c.save()

            except Datos.DoesNotExist:
                c=Datos(noticia=noticia, url=request.POST['valor'])
                c.save()

        elif action == "Mg":
            datos = Datos.objects.get(noticia=noticia)
            datos.megusta= datos.megusta + 1
            datos.save()

            megusta=Votos(datos=Datos.objects.get(noticia=noticia),usuario=request.user.username,valor="Mg")
            megusta.save()

        elif action == "NoMg":
            datos= Datos.objects.get(noticia=noticia)
            datos.nomegusta= datos.nomegusta + 1
            datos.save()

            nomegusta = Votos(datos=Datos.objects.get(noticia=noticia),usuario=request.user.username,valor="NoMg")
            nomegusta.save()

        elif action == "Borrar contenido":
            try:
                c= Datos.objects.get(noticia=noticia)
                c.delete()
                return redirect('/')

            except Datos.DoesNotExist:
                c=Datos.objects.get(noticia=noticia, url=valor)
                c.save()

        elif action == "Borrar voto":
            datos = Datos.objects.get(noticia=llave)
            borrar_voto = Votos.objects.get(datos=Datos.objects.get(noticia=noticia),usuario=request.user.username)

            if borrar_voto.valor=="Mg":
                datos.megusta= datos.megusta - 1

            elif borrar_voto.valor=="NoMg":
                datos.nomegusta= datos.nomegusta - 1
            datos.save()
            borrar_voto.delete()

        elif action == "Enviar comentario":
            datos = Datos.objects.get(noticia=noticia)
            datos.ncomentarios= datos.ncomentarios + 1

            c = Comentarios(datos=datos, titulo=request.POST['titulo'],
                         comentario=request.POST['comentario'],
                         url= request.POST['url'],
                         fecha=timezone.now(),
                         usuario=request.user.username)
            c.save()
            datos.save()

        elif action == "Nueva Aportacion":
            try:
                c= Datos.objects.get(noticia=noticia)
                c.delete()

            except Datos.DoesNotExist:
                pass

            c=Datos(noticia=noticia, url=request.POST['valor'],usuario=request.user.username,megusta=0,nomegusta=0,ncomentarios=0,fecha=timezone.now())
            c.save()

    try:
        datos=Datos.objects.get(noticia=llave)
        context ={
            'datos': datos,
            'modo':modo
        }

    except Datos.DoesNotExist:
        context = {
            'llave': llave,
            'modo':modo
        }

        if request.GET.get("format") == "xml/":

            XML = loader.get_template('LoVisto/XML.html')
            datos_list = Datos.objects.all()
            contexto = {'datos_list': datos_list}

            return HttpResponse(XML.render(contexto, request))

        if request.GET.get("format") == "json/":

            datos = Datos.objects.filter().values()

            return JsonResponse({"datos_list": list(datos)})
        return render(request, 'LoVisto/RecursoNoEncontrado.html', context)

    datos_list = Datos.objects.all()
    datos_list_3 = datos_list[0:3]
    llave = llave
    comentarios_list = Comentarios.objects.all()
    votos_list = Votos.objects.all()

    datos = Datos.objects.get(noticia=llave)
    url = datos.url

    headers = {'User-Agent': 'Mozilla/5.0'}

    try:
        page = requests.get(url, headers=headers)
        soup = BeautifulSoup(page.text, 'html.parser')

        if "www.reddit.com" in url:
            try:
                text = soup.find("p", class_="_1qeIAgB0cPwnLhDF9XSiJM").text

                # aprobacion = soup.find("div", class_="t4Hq30BDzTeJ85vREX7_M").text
                title = soup.find("title").text

LoVisto/ProyectoFinal/templates/LoVisto/PaginaAEMET.html
{% extends 'LoVisto/PaginaAportacion.html' %}
{%block aportacion%}
<div class="aemet">
<p>{{title}}</p>
<ul>
    <li>Dia:{{fecha}}.</li>
    <li> Temperatura 12-18h: {{temperatura}}</li>
    <li>Temperatura máxima y mínima (°C):{{maxymin}}</li>
    <li>Probabilidad de precipitación:{{precipitacion}}</li>
</ul>
<p>© AEMET. Autorizado el uso de la información y su reproducción citando a AEMET como autora de la misma.
<br>
    <a href={{datos.url}}>Página AEMET</a></p>
</div>
</div>
{%endblock%}

LoVisto/ProyectoFinal/templates/LoVisto/PaginaAportacion.html
{% extends 'LoVisto/schema.html' %}
{%load static%}
{%block cuerpo%}
        <tr>
           <td>
                <table style="width:auto" align="center">
                    <th>{{datos.noticia}}</th>
                    <tr>
                        <td>La Url de la noticia es:</td>
                        <td><a href="{{datos.url}}">{{datos.url}}</td>
                    </tr>
                    <tr>
                       <td>Me gustas : </td>
                        <td>{{ datos.megusta }}</td>
                    </tr>
                    <tr>
                        <td>No me gustas : </td>
                        <td>{{ datos.nomegusta }}</td>
                    </tr>
                    <tr>
                        <td>Fecha de publicacion : </td>
                         <td>{{ datos.fecha }}</td>
                    </tr>
                    <tr>
                        <td>Número de comentarios : </td>
                        <td>{{ datos.ncomentarios }}</td>
                    </tr>
                    <tr>
                        <td>Usuario : </td>
                        <td>{{ datos.usuario }}</td>
                    </tr>
                 </table>

           </td>
        </tr>


        {%if request.user.is_authenticated%}
            {%if datos.votos_set.all%}
                {% for voto in datos.votos_set.all%}

                        {%ifequal voto.usuario request.user.username%}
                            <br> Ya has votado {{voto.valor}}, ¿Lo quieres borrar?

                            <form action="" method ="POST">
                                {% csrf_token %}
                                <td><input class="bt1" type="submit" name="action" value="Borrar voto"></td>
                                </tr>
                            </form>

                        {%else%}
                            <br><br>
                            <table style="width:auto" align="center">
                                <form action="" method ="POST">
                                    {% csrf_token %}
                                    <tr> <td><input class="btlike" type="submit" name="action" value="Mg"></td>
                                </form>

                                <form action="" method ="POST">
                                    {% csrf_token %}
                                    <td><input class="btdislike" type="submit" name="action" value="NoMg"></td>
                                    </tr>
                                </form>
                            </table>
                            <br><br><br>
                        {%endifequal%}
                {%endfor%}
            {%else%}
                <br><br>
                <table style="width:auto" align="center">
                    <form action="" method ="POST">
                        {% csrf_token %}
                        <tr> <td><input class="btlike" type="submit" name="action" value="Mg"></td>
                    </form>

                    <form action="" method ="POST">
                        {% csrf_token %}
                        <td><input class="btdislike" type="submit" name="action" value="NoMg"></td>
                        </tr>
                    </form>
                </table>
                <br><br><br>
            {%endif%}
        {%endif%}
<br><br>
{%block aportacion%}

{%endblock%}


<br><br>
    <p>Comentarios</p>

    {% for comentario in datos.comentarios_set.all%}
        <br>
        <table style="width:auto" align="center">
                    <tr>
                       <td><b>Titulo:</b></td>
                       <td>{{comentario.titulo }}</td>
                    </tr>
                    <tr>
                        <td><b>Cuerpo:</b></td>
                        <td> {{comentario.comentario }}</td>
                    </tr>
                    {%if comentario.url%}
                    <tr>
                        <td><b>Imagen(Opcional):</b></td>
                        <td> <img src={{comentario.url}} width="300"></td>
                    </tr>
                    {%endif%}
                    <tr>
                        <td><b>Usuario:</b></td>
                        <td> {{comentario.usuario }}</td>
                    </tr>
                    <tr>
                        <td><b>Fecha:</b></td>
                        <td>{{ comentario.fecha }}</td>
                    </tr>
        </table>
    {%endfor%}


 <br><br>
    <p>Votos</p>
        {% for voto in datos.votos_set.all%}
                <br>
                <table style="width:auto" align="center">
                            <tr>
                                   <td><b>Usuario:</b></td>
                                   <td>{{voto.usuario }}</td>
                            </tr>
                            <tr>
                                <td><b>Votacion:</b></td>
                                   <td> {{voto.valor }}</td>
                            </tr>
                </table>
        {%endfor%}


{%endblock%}




{%block lateral1%}
{%if request.user.is_authenticated%}
    <p>Introduce nuevo comentario</p>
            <form action="" method ="POST">
                <table style="width:auto" align="left">
                    {% csrf_token %}
                       <tr>
                           <td>Titulo:</td>
                           <td> <input type="text" name="titulo"></td>
                        </tr>
                        <tr>
                           <td> <br>Cuerpo:</td>
                           <td> <input type="text" name="comentario"></td>
                        </tr>
                        <tr>
                           <td> <br>Imagen:</td>
                           <td> <input type="text" name="url"></td>
                        </tr>
            </table> <br> <br> <br>
                    <br/><input class="bt1"  type="submit" name="action" value="Enviar comentario">
                </form>
{% else%}
    <p>Debes iniciar sesion para insertar un comentario</p>
{%endif%}
<br>

    {%ifequal  request.user.username  datos.usuario  %}
         <p>Edita el contenido</p>
            <form action="" method ="POST">
                <table style="width:auto" align="left">
                        {% csrf_token %}
                    <tr>
                       <td> Nuevo cuerpo: </td>
                        <td><input type="text" name="valor"></td>
                    </tr>
                </table>
                <br> <br>
                <input class="bt1" type="submit" name="action" value="Cambiar contenido">
            </form>
            <br>
             <p>Borrar contenido</p>
            <form action="" method ="POST">
                    {% csrf_token %}
                <input class="bt1"type="submit" name="action" value="Borrar contenido">
            </form>
    {%else%}
        <br><br><p>Solo {{ datos.usuario }} puede editar esta publicacion</p>
    {%endifequal%}


<br><br>
 <p>Previsualizacion de la<a href={{datos.url}}> noticia</a></p>
<iframe src="{{ datos.url }}" height="400" width="65%" name="demo">
  <p>Su navegador no es compatible con iframes</p>
</iframe>
<br><br>
{%endblock%}

LoVisto/ProyectoFinal/templates/LoVisto/PaginaAportaciones.html
{% extends 'LoVisto/schema.html' %}
{%load static%}
{%block cuerpo%}
    {%if datos_list%}
        <img src="https://image.flaticon.com/icons/png/512/2964/2964063.png" alt="informacion" width=10% align="center" heigth="50">
    <h1>
        Pagina de todas las aportaciones
    </h1>

        {%for datos in datos_list%}
        <p><a href="{{datos.url}}">{{datos.noticia}}</a> subida por el usuario: {{datos.usuario}}, con {{datos.megusta}}
        me gustas, con {{datos.nomegusta}} no me gustas y con {{datos.ncomentarios}} comentarios</p>
        {%endfor%}

    {%else%}
        <p>No tenemos contenidos que mostrar</p>
    {%endif%}
{% endblock %}

{%block lateral1%}
    <p><br>Aqui podrás ver todas las aportaciones realizadas por los distintos usuarios</br></p>
{% endblock %}

LoVisto/ProyectoFinal/templates/LoVisto/PaginaElMundo.html
{% extends 'LoVisto/PaginaAportacion.html' %}
    {%block aportacion%}
        <div class="elmundo">
        <p>Titulo:</p>
        <p> {{title}}</p>
        <p>{{texto}}</p>
        <img src={{imagen}} width = 300>
        <p>© EL MUNDO. UNIDAD EDITORIAL INFORMACIÓN GENERAL, S.L.U.
        </div>
    {%endblock%}

LoVisto/ProyectoFinal/templates/LoVisto/PaginaElPais.html
{% extends 'LoVisto/PaginaAportacion.html' %}
    {%block aportacion%}
        <div class="elpais">
        <p>Titulo:</p>
        <p> {{title}}</p>
        <p>{{texto}}</p>
        <img src={{imagen}}>
        <p>© EDICIONES EL PAIS S.L.
        </div>
    {%endblock%}

LoVisto/ProyectoFinal/templates/LoVisto/PaginaInformacion.html
{% extends 'LoVisto/schema.html' %}
{%block cuerpo%}
<h1>Información</h1>
{%load static%}
<img src="https://image.flaticon.com/icons/png/512/1/1176.png" alt="informacion" width=10% align="center" heigth="50">
<p>
    <br>Autoría: Pablo Cabeza Portalo
</p>
<p>
    <br>Para el desarrollo de esta aplicación web hemos utilizado:
    <br>-Lenguaje: Python 3.8.5.
    <br>-IDE de Python para desarrolladores: PyCharm 2021.1.2
    <br>-Framework: Django 3.0.3
    <br>Todo ello aplicado al Sistema Operativo de Ubuntu
</p>

<p>
    <br>Funcionalidad de la web:
</p>
<p>
    <br>En esta web podrás ver todas las noticias que suben los usuarios y podrás votar y comentar en cada una de ellas.
    <br>También, si te registras, podrás añadir tus propias noticias para que los demás usuarios puedan votar y comentarla.
    <br>Cada usuario tendrá una página personal en la que verá cada noticia, voto y comentario que ha realizado.
    <br>
</p>
<p>
    <br>Información adicional:
<p/>
<p>
    <br>Para adaptar la web a los diferentes dispositivos, hemos descargado bootstrap 5.0.1
    <br>Hemos implementado una previsualización de las diferentes urls añadidas mediante iframe.
    <br>Aparte de los recursos reconocidos como Reddit, AEMET y Wikipedia, hemos añadido dos más: El Pais y El Mundo.
<p/>
{% endblock %}

{%block lateral1%}
<p><br>En esta pagina se encuentra la información de como se realizo esta web</br></p>
{%endblock%}

LoVisto/ProyectoFinal/templates/LoVisto/PaginaNoReconocido.html
{% extends 'LoVisto/PaginaAportacion.html' %}
{%block aportacion%}
<div class="og">
  <p>Recurso no reconocido en nuestra plataforma, hemos podido extraer esta informacion</p>
  <p>Este es el titulo:{{title}}</p>
  <img src={{imagen}} width="300">
  <a href={{datos.url}}>Artículo
  original</a>
</div>
{%endblock%}

LoVisto/ProyectoFinal/templates/LoVisto/PaginaPrincipal.html
{% extends 'LoVisto/schema.html' %}
{%load static%}
{%block cuerpo%}
    {%if datos_list_10%}

        <img src="https://image.flaticon.com/icons/png/512/2965/2965851.png" alt="informacion" width=10% align="center" heigth="50">
    <h1>
        Bienvenido a "LO VISTO" {{request.user.username}}
    </h1>
           {%for datos in datos_list_10%}
<br><br>
                        <table style="width:auto" align="rigth">
                        <style>a {color: green}</style>
                        <th><a href="{{datos.noticia}}">{{datos.noticia}}</a></th>
                        <tr>
                            <td>La Url de la noticia es:</td>
                            <td><a href="{{datos.url}}">{{datos.url}}</a></td>
                        </tr>
                        <tr>
                           <td>Me gustas : </td>
                            <td>{{ datos.megusta }}</td>
                        </tr>
                        <tr>
                            <td>No me gustas : </td>
                            <td>{{ datos.nomegusta }}</td>
                        </tr>
                        <tr>
                            <td>fecha de publicacion : </td>
                             <td>{{ datos.fecha}}</td>
                        </tr>
                          <tr>
                            <td>Publicado por : </td>
                             <td>{{ datos.usuario }}</td>
                        </tr>
                        <tr>
                            <td>numero de comentarios : </td>
                            <td>{{ datos.ncomentarios}}</td>
                        </tr>
                     </table>
               </td>
            </tr>
        {%endfor%}
    {%else%}
        <p>Aún no hay contenido disponible...</p>
    {%endif%}

{% endblock %}
{%block lateral1%}
    {%  if request.user.is_authenticated%}
        <br>
        <p>Introduce noticia:<p>
        <form action="" method ="POST">
             {% csrf_token %}
            <table style="width:auto" align="left">
               <tr>
                   <td>Noticia:</td>
                   <td><input type="text" name="noticia"></td>
               </tr>
                <tr>
                     <td>Url:</td>
                     <td><input type="text" name="url"></td>
                </tr>
            </table>
    <input class="bt2" type="submit" name="action" value="Insertar" >
        </form>
  {% else %}
    <br><br>

    <p>Para poder introducir un contenido necesitas estar autenticado</p>
    {%endif%}
{% if request.user.is_authenticated%}
        {%if datos_list%}
<br><br>
            Aportaciones de {{request.user.username}}:
             {%for datos in datos_list%}
<br>
                 {% ifequal datos.usuario request.user.username %}
                        <a href="{{datos.url}}">{{datos.noticia}}</a>
                 {%endifequal%}
            {%endfor%}
             <br>

        {%endif%}
  {%endif%}
{% endblock %}

LoVisto/ProyectoFinal/templates/LoVisto/PaginaReddit.html
{% extends 'LoVisto/PaginaAportacion.html' %}
    {%block aportacion%}
        <div class="reddit">
        <p>Nota Reddit: {{title}}</p>
        <p>{{texto}}</p>
        <p>{{imagen}}</p>
        <p><a href="https://www.reddit.com/r/django/comments/n842st">Publicado
        en [subreddit]</a>. Aprobación: {{aprob}}.</p>
        </div>
    {%endblock%}

LoVisto/ProyectoFinal/templates/LoVisto/PaginaUsuario.html
{% extends 'LoVisto/schema.html' %}
{%block cuerpo%}
<h1>Bienvenido a tu perfil, {{request.user.username}}</h1>
<br>Podrás ver todas las noticias, comentarios y votos de forma segura en esta página</br>
{%if datos_list%}
<br><br>
<p>Mis publicaciones:</p>
 {%for datos in datos_list%}
             {% ifequal datos.usuario request.user.username %}
 <br>
                <table style="width:auto" align="center">
                    <style>a {color: red}</style>
                    <th><a href="/{{datos.noticia}}">{{datos.noticia}}</a></th>
                    <tr>
                        <td>La Url del valor  es:</td>
                        <td><a href="{{datos.url}}">{{datos.url}}</a></td>
                    </tr>
                    <tr>
                       <td>votos positivos : </td>
                        <td>{{ datos.megusta }}</td>
                    </tr>
                    <tr>
                        <td>votos negativos : </td>
                        <td>{{ datos.nomegusta }}</td>
                    </tr>
                    <tr>
                        <td>fecha de publicacion : </td>
                         <td>{{ datos.fecha }}</td>
                    </tr>
                    <tr>
                        <td>numero de comentarios : </td>
                        <td>{{ datos.ncomentarios }}</td>
                    </tr>
                 </table>
             {%endifequal%}
        {%endfor%}
<br>
{%else%}
        <p>No tenemos contenidos que mostrar</p>
{%endif%}
<p>Tus comentarios</p>
        {%if comentarios_list%}
            {%for comentarios in comentarios_list%}
                {% ifequal comentarios.usuario request.user.username %}
                    <br>
                    <table style="width:auto" align="center">
                                <tr>
                                    <td><b>Titulo comentario:</b></td>
                                    <td>{{comentarios.titulo }}</td>
                                </tr>
                                 <tr>
                                     <td><b>tema comentado:</b></td>
                                     <td>{{comentarios.datos.noticia }}</td>
                                </tr>
                                <tr>
                                    <td><b>Cuerpo:</b></td>
                                    <td> {{comentarios.comentario }}</td>
                                </tr>
                                {%if comentarios.url%}
                                <tr>
                                    <td><b>Imagen:</b></td>
                                    <td> <img src={{comentarios.url}} width="300"></td>
                                </tr>
                                {%endif%}
                                <tr>
                                    <td><b>Fecha:</b></td>
                                    <td>{{ comentarios.fecha }}</td>
                                </tr>
                    </table>

                {%endifequal%}
            {%endfor%}
        {%else%}
            <br>No hay contenido disponible todavía.</br>
        {%endif%}
 <br> <br> <br>
 <br> <br> <br>
{%endblock%}
{%block lateral1%}
<p>Tus votos:</p>
<br>
{%if votos_list%}
        {%for votos in votos_list%}
            {% ifequal votos.usuario request.user.username %}
                <table style="width:auto" align="left">
                    <tr>
                        <td><b>Valor del voto :<b/></td>
                        <td>{{votos.valor }}</td>
                    </tr>
                    <tr>
                        <td><b>tema votado:<b/></td>
                         <td>{{votos.datos.noticia }}</td>
                    </tr>

                </table>
                <br> <br> <br>
            {%endifequal%}
        {%endfor%}
{%else%}
    <br>No hay contenido disponible todavía.</br>
{%endif%}
{% endblock %}

LoVisto/ProyectoFinal/templates/LoVisto/PaginaWikipedia.html
{% extends 'LoVisto/PaginaAportacion.html' %}
{%block aportacion%}
<div class="wikipedia">
  <p>Artıculo Wikipedia: {{title}}</p>
  <img src={{imagen}} width="300">
  <p>{{texto}}</p>
  <p>© WIKIPEDIA. El texto está disponible bajo la Licencia Creative Commons Atribución Compartir Igual 3.0; pueden aplicarse cláusulas adicionales. Al usar este sitio, usted acepta nuestros términos de uso y nuestra política de privacidad.
Wikipedia® es una marca registrada de la Fundación Wikimedia, Inc., una organización sin ánimo de lucro.
  <a href={{datos.url}}>Pagina Wikipedia</a>
</div>
{%endblock%}